name       : perl-business-issn
version    : '1.003'
release    : 5
source     :
    - https://github.com/briandfoy/business-issn/archive/release-1.003.tar.gz : c86dc522b9f42d0a14c1a822062a092bb749e19b9fc3d58952effe0199f4f311
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/briandfoy/business-issn
summary    : Business::ISSN - Perl extension for International Standard Serial Numbers
description: |
    Business::ISSN - Perl extension for International Standard Serial Numbers
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
