name       : perl-business-issn
version    : '1.005'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-1.005.tar.gz : 3b09b0267f0a6660fb92b6f50c4c7796ef6a263b62ad3bbeaa07189a0c7c39b3
homepage   : https://metacpan.org/pod/Business::ISSN
license    : Artistic-2.0
component  : programming.perl
summary    : Business::ISSN - Perl extension for International Standard Serial Numbers
description: |
    Business::ISSN - Perl extension for International Standard Serial Numbers
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
