name       : perl-business-issn
version    : '1.004'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-1.004.tar.gz : 97ecab15d24d11e2852bf0b28f84c8798bd38402a0a69e17be0e6689b272715e
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/briandfoy/business-issn
summary    : Business::ISSN - Perl extension for International Standard Serial Numbers
description: |
    Business::ISSN - Perl extension for International Standard Serial Numbers
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
