name       : perl-business-issn
version    : 0.91
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-0.91.tar.gz : f15b192c0f547bb2967811072b3d343b94bc5ea58d02704c19122f7ae0a9d6b5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Business::ISSN - Perl extension for International Standard Serial Numbers
description: |
    Business::ISSN - Perl extension for International Standard Serial Numbers
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
